name: Build and Publish package

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Get version from package.json
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: projects/angular-tabler-icons

      - name: Build Angular library
        run: npm run lib:build

      - name: Run unit tests
        run: npm run test -- --no-watch

      - name: Publish package to NPM with OIDC
        working-directory: ./dist/angular-tabler-icons
        run: npm publish --access public --provenance

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.current-version }}
          name: Release v${{ steps.version.outputs.current-version }}
          body: |
            ## Changes in this Release

            For detailed changes, please refer to the [CHANGELOG](https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md).
          draft: false
          prerelease: false
          generate_release_notes: true
